image: maven:3.3.9-jdk-8

stages:
  - build
  - test

include:
  template: Jobs/Code-Quality.gitlab-ci.yml

build:
  stage: build
  script: "mvn clean package"
  artifacts:
    name: "antiRedstoneClock"
    paths:
      - "DIST/target/*.jar"
    expire_in: 1 week

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]
