name: AntiRedstoneClock
version: 1.1.1-IMPROVEPERFTEST1
description: Limit the redstoneClock
author: Amosar
website: https://www.spigotmc.org/resources/antiredstoneclock.18557
api-version: 1.13
softdepend: [WorldGuard, bstats, PlotSquared]

main: com.trafalcraft.antiRedstoneClock.Main

commands:
   antiRedstoneClock:
     description: Base command for the antiRedstoneClock plugin.
     aliases: [arc]
